# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20161108_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partial',
            name='object_type',
            field=models.CharField(choices=[('image', 'image'), ('text', 'text'), ('video', 'video')], max_length=16),
        ),
    ]
